### ISSUE TITLE
Discord font not working

### ISSUE THREAD

**Issue by Teslahaha** [OnscreenProton/deepbluetheme#1]
The Discord font for the wordmark ("DEEPBLUETHEME") doesn't work and there is no link for me to download it.
![image](https://user-images.githubusercontent.com/17229240/124982888-44489d80-e005-11eb-91ca-da4a640b52b4.png)

**Comment by OnscreenProton** [comment]
I think I just fixed it? The theme was using a dead link that had previously worked. If it didn't work, [here](https://github.com/powercord-org/powercord-backend/blob/my-awesome-branch/packages/web/src/fonts/discord-font.otf?raw=true) is a link to the font
